name: netease_meeting_ui
description: A package implements standard UI for netease_meeting.
version: 0.0.1
homepage: https://yunxin.163.com/
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.22.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  device_info_plus: ^8.0.0

  cupertino_icons: ^1.0.5

#  netease_meeting_assets: ^0.1.0-rc.0
  netease_meeting_assets:
    path: ../meeting_kit_assets
#  netease_common: ^0.0.1-rc.1
  netease_common: 0.0.3-rc.0

  bot_toast: ^4.0.2
  permission_handler: ^10.0.0

  path_provider: ^2.0.11
  uuid: ^3.0.6
  pedantic: ^1.11.1
  wakelock: ^0.6.2
  wakelock_platform_interface: ^0.3.0
  shared_preferences: ^2.0.15

  image_size_getter: ^2.1.2
#  image_gallery_saver: ^1.7.1
#  open_file:
#    path: ../../third_party/open_file
  open_filex: ^4.0.0
  scrollable_positioned_list: ^0.3.5

  file_picker: ^5.0.0
#  file_picker:
#    path: ../../third_party/file_picker

  netease_meeting_core:
    path: ../meeting_kit
  netease_roomkit: 1.16.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  generate: true
  plugin:
    platforms:
      android:
        package: com.netease.meeting.plugin
        pluginClass: MeetingPlugin
      ios:
        pluginClass: MeetingPlugin
